### ISSUE TITLE
Use HTTP Authorisation

### ISSUE THREAD

**Issue by thepushkarp** [iiitv/getmein-web#107]
The GitHub team sent this reminder about the deprecation issue.

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

**Comment by thepushkarp** [comment]
Anyone from @iiitv/batch-of-2022 or @iiitv/batch-of-2023 who'd like to take this issue up?

**Comment by AmanRaj1608** [comment]
@solankidivyam @prathmeshkhandelwal1 @ShivanshKumar

Is anyone Interested?

At line 167 in `server.js` file, we are using 
```js
    const url = `https://api.github.com/teams/${codes[pref]}/memberships/${username}?access_token=${token}`
    console.log(url)
    axios
      .put(url)
      .then(res => {
        console.log(res.data.url)
        resolve(200)
      })
      .catch(error => {
        reject(error)
      })
  })

```

You have to set the header in Axios and remove the access_token param.
Something just like this.

```js
headers: {
    Authorization: 'token ' + token
}
```
