### ISSUE TITLE
Add Dark/Light Mode

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#11]
Add one toggle to change color scheme

**Comment by singhpratyush** [comment]
I don't see why this would be needed. The time one spends on the website is too less for the need to having a feature to toggle themes.

**Comment by boat46450** [comment]
#19 I already solve it

**Comment by AmanRaj1608** [comment]
@aashutoshrathi 
I think I can complete this from where @boat46450 left.
Please assign me if this issue is still available
