### ISSUE TITLE
Refactor Codebase

### ISSUE THREAD

**Issue by thepushkarp** [iiitv/getmein-web#111]
When the project started, the project did well with hardcoded values like `team_ids` but now with the teams increasing, we should fetch them from API.

A refactoring overhaul is much needed.

Tip: Use principles taught in CS303 Course :wink:

**Comment by anshumanv** [comment]
Could be a good issue for the event next month 🤞

**Comment by aashutoshrathi** [comment]
Yeah, I think we can even tip some BAT 😄

**Comment by prathmeshkhandelwal1** [comment]
Can you explain this issue little bit more @AmanRaj1608  @thepushkarp ? it will be helpful for me as i dont know about CS303 course xD.

**Comment by aashutoshrathi** [comment]
@prathmeshkhandelwal1 This issue mainly points out to:
- the codebase should follow DRY
- consistent linting 
- consistent use of paradigms (Eg: either `.then` or `async-await`)
- using JS inbuilt to reduce lines of code.
And many more.
Please add more info @iiitv/project-maintainers

**Comment by prathmeshkhandelwal1** [comment]
@iiitv/project-maintainers Can you provide more info?

**Comment by anujpuri72** [comment]
@prathmeshkhandelwal  what else do you want to know?
As of now API creation and code refactoration needs to be done  A said by @thepushkarp

**Comment by yashshah2820** [comment]
@prathmeshkhandelwal1 go through the codebase you will find that there are some code blocks repeated, fix that using the DRY principles and follow the points mentioned by @aashutoshrathi sir

**Comment by thepushkarp** [comment]
I think we don't need this issue now.
