### ISSUE TITLE
Page doesn't open in new tab

### ISSUE THREAD

**Issue by RohithChittibommala** [iiitv/getmein-web#126]
## Expected Behavior
when we click on the social icons the page should open in a new tab
 It would be better if the page opens in a new tab

## Current Behavior and Triggers
  when we click on the social icons the page doesn't open in a new tab
  The user experience would be  better if the page opens in a new tab

## Possible Solution
 The above issue can be fixed by adding the target attribute ;
  adding target attribute fixes this issue

## Would you like to work on this issue?
Yes

**Comment by RohithChittibommala** [comment]
@AmanRaj1608  @aashutoshrathi  @iiitv-project-maintainers can I work on this issue

**Comment by RohithChittibommala** [comment]
@aashutoshrathi  sir when I tried to commit changes I am getting this  error 

![error](https://user-images.githubusercontent.com/62145732/94265689-93ca4b00-ff56-11ea-99d1-8cf53fe2afa5.png)

**Comment by aashutoshrathi** [comment]
https://github.com/iiitv/getmein-web/issues/54#issuecomment-696564441

**Comment by DMRathod** [comment]
Is this issue is still open?

**Comment by RohithChittibommala** [comment]
> Is this issue is still open?
no
