### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [iiitv/getmein-web#127]
## Expected Behavior

All the API's call should be working.

## Current Behavior and Triggers

Many features are blocked due to CORS error in API call.

## Possible Solution

I tried many soln, it did'nt work at all, i also tried stackoverflow soln but it also did'nt  worked.
Adding this link https://cors-anywhere.herokuapp.com/ before all the api links will work but it will make app too slow.
Can you suggest any other soln.

## Would you like to work on this issue?

Yes

## Screenshot of issue

![Screenshot (117)](https://user-images.githubusercontent.com/56167998/94200820-ae5ddf00-fed8-11ea-9cde-b7dd4fa3e091.png)

**Comment by aashutoshrathi** [comment]
Oh! This is probably my mistake, can you try using `https://api.aashutosh.dev` instead of `http://aashutoshrathi.glitch.me/`
If needed I'll add this as an allowed domain in my server

**Comment by prathmeshkhandelwal1** [comment]
okk Sir, I will try this.

**Comment by prathmeshkhandelwal1** [comment]
and let you know if some issue occurs.

**Comment by prathmeshkhandelwal1** [comment]
![Screenshot (118)](https://user-images.githubusercontent.com/56167998/94243217-b9def380-ff34-11ea-9051-a2fe07f70941.png)
@aashutoshrathi Sir it is again showing same error, you can check it in console on above img.

**Comment by aashutoshrathi** [comment]
Can you add CORS anywhere over it and check if it is working?

**Comment by aashutoshrathi** [comment]
If it works with it, simply push the code as of now, I have whitelisted this URL in API.

**Comment by prathmeshkhandelwal1** [comment]
> Can you add CORS anywhere over it and check if it is working?

Do you mean i have to add `mode: 'cors',
      headers: {
      'Access-Control-Allow-Origin':'*'
      }` in my fetch call?

**Comment by aashutoshrathi** [comment]
No, I meant to use `https://cors-anywhere.herokuapp.com/`

**Comment by prathmeshkhandelwal1** [comment]
Sure sir doing a pr today @aashutoshrathi

**Comment by prathmeshkhandelwal1** [comment]
> https://cors-anywhere.herokuapp.com/

I used this link but still it is giving 404 error.

![Screenshot (120)](https://user-images.githubusercontent.com/56167998/94462990-e8c9c380-01d9-11eb-98a2-aceef2b5902b.png)

**Comment by prathmeshkhandelwal1** [comment]
> > https://cors-anywhere.herokuapp.com/
> 
> I used this link but still it is giving 404 error.
> 
> ![Screenshot (120)](https://user-images.githubusercontent.com/56167998/94462990-e8c9c380-01d9-11eb-98a2-aceef2b5902b.png)

but CORS is solved, should i do a PR?

**Comment by aashutoshrathi** [comment]
The URL is wrong. `api.aashutosh.dev/gh` should be used and also make a PR at once

**Comment by prathmeshkhandelwal1** [comment]
> The URL is wrong. `api.aashutosh.dev/gh` should be used and also make a PR at once

sure sir

**Comment by prathmeshkhandelwal1** [comment]
After CORS get fixed there is no [messege](https://github.com/iiitv/getmein-web/blob/5b330c8687316c028fa04d117be696cb52bf6c9e/public/client.js#L31) property on the response 
![Screenshot (123)](https://user-images.githubusercontent.com/56167998/95040240-b4319c80-06f0-11eb-803d-1bc386f9314d.png)

as it was mentioned in the code and hence it was also not working, So I replaced it with error as of my understanding and its working now.

![Screenshot (124)](https://user-images.githubusercontent.com/56167998/95040251-ba277d80-06f0-11eb-8e6d-19f02ff2d9bd.png)

**Comment by prathmeshkhandelwal1** [comment]
> After CORS get fixed there is no [messege](https://github.com/iiitv/getmein-web/blob/5b330c8687316c028fa04d117be696cb52bf6c9e/public/client.js#L31) property on the response
> ![Screenshot (123)](https://user-images.githubusercontent.com/56167998/95040240-b4319c80-06f0-11eb-803d-1bc386f9314d.png)
> 
> as it was mentioned in the code and hence it was also not working, So I replaced it with error as of my understanding and its working now.
> 
> ![Screenshot (124)](https://user-images.githubusercontent.com/56167998/95040251-ba277d80-06f0-11eb-8e6d-19f02ff2d9bd.png)

Should I do the PR?
