### ISSUE TITLE
Invite to Slack

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#15]
If the email address is from IIITV, invite the member to Slack too.

Resource: https://api.slack.com/methods/channels.invite

**Comment by mddanishyusuf** [comment]
@aashishyadavally can I take this forward? If this is not done.

**Comment by aashutoshrathi** [comment]
Sure and it's @aashutoshrathi

**Comment by mddanishyusuf** [comment]
@aashutoshrathi what is the domain name of the IIITV members?

**Comment by Monal5031** [comment]
`iiitvadodara.ac.in` or `iiitv.ac.in`

**Comment by mddanishyusuf** [comment]
Here what I understood.

1. Get the users list from slack group https://api.slack.com/methods/apps.permissions.users.list
2. Then get the user id from the list through email/username
3. Check the email is blog to IIITV group then send the invitation link
4. Send Link https://api.slack.com/methods/channels.invite

or Invite the new member on the slack ? https://stackoverflow.com/a/36114710/4589440

Let me know, please. Thanks

**Comment by aashutoshrathi** [comment]
This issue simply means that while calling add member function on decrypting the URL, use the decrypted email and send the slack invite for iiitvadodara.slack.com too.

@mddanishyusuf I hope that helps

**Comment by aashutoshrathi** [comment]
@mddanishyusuf Use your keys in .env file locally and add a variable in code, I'll make sure deployment uses mine.

**Comment by mddanishyusuf** [comment]
https://github.com/slackhq/slack-api-docs/issues/30 just for notes
