### ISSUE TITLE
Add Issue Template

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#20]
Add an issue template, helping people to elaborate issues more.

**Comment by DipanshKhandelwal** [comment]
Assign this to me @aashutoshrathi

**Comment by ABHISHEK-G0YAL** [comment]
done #hactoberfest

**Comment by DipanshKhandelwal** [comment]
@aashutoshrathi He has already sent a PR. No problem with that :+1: . Go ahead with it.
