### ISSUE TITLE
Add a PR Template

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#21]
Add PR template to help reviewers to know which issue is referenced and what changes are done with a demo.

**Comment by DipanshKhandelwal** [comment]
Assign this to me @aashutoshrathi

**Comment by Ananthavijay** [comment]
can I work on this?

**Comment by aashutoshrathi** [comment]
Go on @Ananthavijay

**Comment by Ananthavijay** [comment]
thanks

**Comment by ABHISHEK-G0YAL** [comment]
done

**Comment by Ananthavijay** [comment]
@ABHISHEK-G0YAL Pls see the issue is assigned to me.
