### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#25]
Add a .editorconfig file.

**Comment by supriyanta** [comment]
Where do I add it?
In the main directory?

**Comment by ABHISHEK-G0YAL** [comment]
done

**Comment by aashutoshrathi** [comment]
@iiitv/batch-of-2022 Anyone up for this?

**Comment by AmanRaj1608** [comment]
Yes, I want to try 🙋‍♂️

**Comment by coder-cracker** [comment]
Yes

**Comment by Utiwari1999** [comment]
@aashutoshrathi
Yes

**Comment by aashutoshrathi** [comment]
Feel free to send relevant PR and it will be merged. 😄

**Comment by AmanRaj1608** [comment]
@aashutoshrathi  
Is this PR #60  relevant ?
I have made it as per indentation of project 😅

**Comment by aashutoshrathi** [comment]
Mentors are reviewing wait for it. 😄
