### ISSUE TITLE
Fix instant username check

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#3]
Currently, the function checks if the username exists or not, but there are some issues with function.

Also, we have to add classes to the input box,
i.e. on receiving 200: `addClass('uk-form-success')` and on 404: `addClass('uk-form-danger')`

https://github.com/iiitv/getmein-web/blob/0240d978bf197f2a83b5e5888f76c8af9464a247/public/client.js#L9-L27

**Comment by mohitkyadav** [comment]
What's the bug?
Please explain.

**Comment by aashutoshrathi** [comment]
Currently the function, checks if username exists or not, but there are some issues with function and also when fixed, we have to add classes to the input box, i.e. on recieving 200: `addClass('uk-form-success')` and on 404: `addClass('uk-form-danger')`

https://github.com/iiitv/getmein-web/blob/0240d978bf197f2a83b5e5888f76c8af9464a247/public/client.js#L9-L27

**Comment by rossoskull** [comment]
@aashutoshrathi I have tried fixing this bug, I am able to add the classes 'uk-form-success' and 'uk-form-danger', but the styles aren't updated. Working on it.
