### ISSUE TITLE
Problem with no scrolling in phones

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#36]
## Expected Behavior

The whole page should be visible on all devices.

## Current Behavior and Triggers

Page gets trimmed for small screens.

## Possible Solution

Enable scroll again.

## Would you like to work on this issue?

No

**Comment by lucas-barros** [comment]
Hi, I'm going to work on this

**Comment by LoganArnett** [comment]
Opened a PR for this issue, hope it helps
