### ISSUE TITLE
Add pre-hook commit to force eslint rules

### ISSUE THREAD

**Issue by rahulrana95** [iiitv/getmein-web#39]
## Expected Behavior

Whenever someone wants to do some commit eslint should run so
that we have consistent coding style
## Current Behavior and Triggers
no enforcing of style guidelines

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by marcelorl** [comment]
on it
