### ISSUE TITLE
Read transport config from env

### ISSUE THREAD

**Issue by anshumanv** [iiitv/getmein-web#55]
Refer - https://github.com/iiitv/getmein-web/blob/f6800f60860dccfc22ca1b001ea6471a9f1f80c5/server.js#L50

**Comment by aashutoshrathi** [comment]
@iiitv/batch-of-2022 Anyone up for this?

**Comment by AmanRaj1608** [comment]
ok will try
can you explain a little what to do

**Comment by aashutoshrathi** [comment]
This issue simply says that instead of entering values in the line.
```
    host: 'smtp.gmail.com',
    secure: true,
    port: '465',
    pool: true,
```
Get the values from a env variable.
