### ISSUE TITLE
Update createmail.js's Styles

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#57]
Currently, the images are not sized properly.
Send yourself an email and check for the issue.

**Comment by pAditya198** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/42460356/56202779-6723bb80-6061-11e9-9d0f-16417d55c9c2.png)

**Comment by pAditya198** [comment]
The debugging has been done, and that is the output.
