### ISSUE TITLE
Add Email Template

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#6]
Add email template and encrypt the invite link into it.
On clicking the link, it should decrypt and proceed to team pages of iiitv.

**Comment by yashLadha** [comment]
Firstly you should create a table structure for the email template and then the link that is sent to the user should be encrypted. @rossoskull

**Comment by aashutoshrathi** [comment]
@rossoskull if you are working on this issue, please update us.
Resources you can really use: [confirm email in node-express](https://stackoverflow.com/questions/39092822/how-to-do-confirm-email-address-with-express-node) and [node-rsa](https://www.npmjs.com/package/node-rsa)

**Comment by rossoskull** [comment]
Yes, I am working on this issue. Thanks for the resources :)

**Comment by aashutoshrathi** [comment]
@rossoskull hurry up on this one, as people are using getmein-web to join org.
