### ISSUE TITLE
[Feature] Add ESLint

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#61]
## Expected Behavior

You have to add a default linter. Preferable - ESLint

You can take help from #38

**Comment by aashutoshrathi** [comment]
@iiitv/batch-of-2022 Another task for you people.
Grab it. 😃

**Comment by thepushkarp** [comment]
@aashutoshrathi I would like to work on this issue

**Comment by thepushkarp** [comment]
@aashutoshrathi Is there a particular coding style that also needs to be enforced?

**Comment by aashutoshrathi** [comment]
Default of ESLint will work, right @yashLadha?

**Comment by yashLadha** [comment]
Yes, as this is a very small project, setting basic plugins like single quotes, line length, and const and let checks would be sufficient.
