### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#66]
Add Travis CI, so that we can check for Linit and other errors in CI's environment itself.

**Comment by thepushkarp** [comment]
@aashutoshrathi Sir, I want to try this issue.
Can you explain this a bit?

**Comment by aashutoshrathi** [comment]
You have to add Travis to this repo, such that it executes few commands:
```sh
npm i
npm lint
```
So. that whenever there are lint errors, the build fails

**Comment by yashLadha** [comment]
Kudos for explanation @aashutoshrathi 👏

**Comment by yashLadha** [comment]
Before going for this issue, please note to have your previous pr's merged before that

**Comment by yashLadha** [comment]
Fixes #64

**Comment by thepushkarp** [comment]
After adding Travis, should Husky still run the tests before each commit and push?
