### ISSUE TITLE
Fix tooltips of footer social links

### ISSUE THREAD

**Issue by rossoskull** [iiitv/getmein-web#71]
## Expected Behavior

Decrease the offset of the tooltip so they appear near the icons.

## Current Behavior and Triggers

Tooltips of the footer social link icons seem to have a high value of offset.
![ezgif-1-025f5544468f](https://user-images.githubusercontent.com/27884543/57147619-9e29f900-6de5-11e9-8a92-4eb852c667d0.gif)

## Would you like to work on this issue?

No.

**Comment by aashutoshrathi** [comment]
![](http://18.191.101.110/wp-content/uploads/2017/10/Works-on-machine.gif)

**Comment by rossoskull** [comment]
Closing this issue as it was fixed in the new deployment :tada:
