### ISSUE TITLE
Footer containing links overlaps with body on small screens

### ISSUE THREAD

**Issue by thepushkarp** [iiitv/getmein-web#78]
## Expected Behavior

The footer containing the links should appear below the body. If there is less screen space, it should appear below after scrolling and not on top of it.

## Current Behavior

On small screens and in landscape mode, this overlapping happens.

![Annotation 2019-05-16 023836](https://user-images.githubusercontent.com/42088801/57809857-16000800-7784-11e9-80ca-7694ca714a40.png)

## Your Environment

On most mobile browsers in landscape mode or while typing.

## Would you like to work on this issue?

No

**Comment by AmanRaj1608** [comment]
I think it's maybe because we removed y-scroll in #72 🤔

**Comment by aashutoshrathi** [comment]
@AmanRaj1608 Feel free to experiment and send a PR

**Comment by AmanRaj1608** [comment]
@thepushkarp @aashutoshrathi 
Fixed issue please review 😁
