### ISSUE TITLE
No scroll on small screens

### ISSUE THREAD

**Issue by thepushkarp** [iiitv/getmein-web#81]
## Expected Behavior

On screens with height big enough, all the content is displayed so there's no need to scroll but on small screens, scrolling is needed to see all the content.

## Current Behavior and Triggers

No scrollbar on small screens
Might be related to #70 and #78 

On Landscape Mode in Android
![image](https://user-images.githubusercontent.com/42088801/58097901-0eae8380-7bf6-11e9-8b6a-3eb1f620bad2.png)

In small Window
![image](https://user-images.githubusercontent.com/42088801/58098069-65b45880-7bf6-11e9-9fc1-e902536358ce.png)

## Your Environment

Tested on Edge (Chromium Dev and Default) on Windows, and Chrome on Android

## Would you like to work on this issue?

No

**Comment by AmanRaj1608** [comment]
Well I tried to fix that with `uk-overflow-auto` and `uk-scrollable-box` but neither helped.
I thought it was something about UIkit class but even adding css class didn't changed anything
```css
@media screen and (max-height: 450px) {
  body { overflow: auto; } /* Or change the height or whatever */ 
}
```

I am unable to solve it if @aashutoshrathi sir could help 😔

**Comment by aashutoshrathi** [comment]
Started with reverting that merge, I would recommend you to try once again.
I think its a smaller one.
I'll fire a PR during the weekend otherwise.

**Comment by AmanRaj1608** [comment]
@aashutoshrathi 
Yes thanks I got what I was doing wrong 
I have created a PR #84 please review it.

**Comment by thepushkarp** [comment]
This issue is resolved now.
