### ISSUE TITLE
Issue when toggling Dark/Light themes

### ISSUE THREAD

**Issue by vrajparesh** [iiitv/getmein-web#85]
## Expected Behavior
      The font in the textbox, when toggling the website from Black Theme to white theme, should be visible

## Current Behavior and Triggers
 It shows white font, thus on toggling , the font is not visible, unless we edit the data.

## Possible Solution

if we could adjust the font-color on toggling the themes.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):Chrome 74.0.3729.169 (Official Build) (64-bit
* Operating System and version (desktop or mobile): Windows 10 x64, Desktop
* Link to your project:

## Would you like to work on this issue?

No

Images, showing this issue, are attached
![image](https://user-images.githubusercontent.com/10117584/58427465-54b78b80-80bd-11e9-9adc-48fe23290e4d.png)
![image](https://user-images.githubusercontent.com/10117584/58427501-6f8a0000-80bd-11e9-8716-b7b717fd22a9.png)

**Comment by AmanRaj1608** [comment]
**I didn't get the issue. Can you please explain more.**  😅

![image](https://user-images.githubusercontent.com/42104907/58429055-3a33e100-80c2-11e9-8594-d2a99d28ad53.png)

**Comment by vrajparesh** [comment]
> **I didn't get the issue. Can you please explain more.** 😅
> 
> ![image](https://user-images.githubusercontent.com/42104907/58429055-3a33e100-80c2-11e9-8594-d2a99d28ad53.png)


[issue.zip](https://github.com/iiitv/getmein-web/files/3224405/issue.zip)


This zip encloses a Video which somewhat explains the issue

**Comment by AmanRaj1608** [comment]
So when we fill text using suggestion box it is invisible 🤔

**Comment by AmanRaj1608** [comment]
I think it can be fixed by adding ` autocomplete="off" ` in  `<input > ` . I will send a PR after my #84 is merged.

**Comment by aashutoshrathi** [comment]
@AmanRaj1608 Try to find another solution

**Comment by AmanRaj1608** [comment]
@aashutoshrathi 
Yes I think removing a feature like auto complete is bad for a developer. 
I will try to change colour of text and open a PR

**Comment by AmanRaj1608** [comment]
@aashutoshrathi 

**Sir I changed colour of of text and I think it will solve the issue. Is this okay ? Should I open a PR ?**
<br>
![image](https://user-images.githubusercontent.com/42104907/58829350-404b3400-8665-11e9-8c10-1a09f9ec6cb4.png)

Changes GIF -  https://drive.google.com/file/d/1Rt0w0rmy8E6AzZijl1A9pItAn8dS7pHi/view

**Comment by prathmeshkhandelwal1** [comment]
I want to work on this @iiitv/project-maintainers

**Comment by anujpuri72** [comment]
Go for it 👍 @prathmeshkhandelwal1
