### ISSUE TITLE
Wrong Username

### ISSUE THREAD

**Issue by pAditya198** [iiitv/getmein-web#87]
When I enter a wrong GitHub username instead of error it send a verification mail.

![Screenshot (25)](https://user-images.githubusercontent.com/42460356/58892088-3ed44700-870b-11e9-8b37-9cb27e57d874.png)
![Screenshot (26)](https://user-images.githubusercontent.com/42460356/58892090-3f6cdd80-870b-11e9-87fb-9536ec0be59c.png)

**Comment by yashLadha** [comment]
Then, in that case use GitHub API to validate data and then send mail.

**Comment by yashLadha** [comment]
Are you up for the issue @pAditya198

**Comment by AmanRaj1608** [comment]
@yashshah2820 
Will this solve the issue 
https://stackoverflow.com/questions/28977164/github-api-how-to-check-user-or-organization-name-availability

**Comment by pAditya198** [comment]
I'll work on the issue. @yashLadha

**Comment by yashLadha** [comment]
As the issue is proposed by @pAditya198 . So it would be legit that he take the initiative. If he is not able to solve it then @AmanRaj1608 you can take it forward.

**Comment by AmanRaj1608** [comment]
Yes @pAditya198  you do it  👍🎉

**Comment by aashutoshrathi** [comment]
Since we are already checking for username, shouldn't we disable the button if any of field is invalid?
