### ISSUE TITLE
Send message to slack when someone gets invited

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#89]
When sending an email, also post to slack.
You can access the webhook URL using `process.env.INVITE_CHANNEL_WEBHOOK` and try to post on your own test channels maybe.

Reference: https://api.slack.com/incoming-webhooks#posting_with_webhooks

**Comment by AmanRaj1608** [comment]
I want to try this. Will send a relevant PR shortly.

**Comment by AmanRaj1608** [comment]
@aashutoshrathi
 
**What kind of message should be sent.**

### 1. Should it be simple like this 

![image](https://user-images.githubusercontent.com/42104907/60554639-f33aaa80-9d55-11e9-94d3-7faff9541a8f.png)

### 2. Or should I use `advanced formatting` like you sent in referance 

![image](https://user-images.githubusercontent.com/42104907/60554755-8378ef80-9d56-11e9-8780-f0dff62caea7.png)

**Comment by aashutoshrathi** [comment]
@AmanRaj1608 Thanks for picking this up.
I would prefer `advanced formatting` and that you just sent relevant field like timestamp, username and invitation sent/
