### ISSUE TITLE
preload stylesheet and async script loading for improve page load time

### ISSUE THREAD

**Issue by yashLadha** [iiitv/getmein-web#93]

**Comment by AmanRaj1608** [comment]
@yashLadha 
If it's open I want to do this.

I am thinking to solve this adding `"preload"` just like explained here 
https://jonbeebe.net/2017/07/preload-styles-and-scripts-to-improve-load-times/

**Comment by yashLadha** [comment]
Yes, you can take it. I am also aligned with the blog post that you have shared. GTG 👍
