### ISSUE TITLE
Auto-update Glitch with GitHub

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#95]
Resources: https://support.glitch.com/t/tutorial-how-to-auto-update-your-project-with-github/8124

**Comment by AmanRaj1608** [comment]
@aashutoshrathi 
I am on it.
Should I use  [node-cmd](https://nodejs.org/api/child_process.html)  over `node-cmd` to run commands.

**Comment by aashutoshrathi** [comment]
@AmanRaj1608 Yeah!
`node-cmd` is fine, but if we can have it without any extra dependency, then its better.
